baseurl                  = "https://www.moritzfriedrich.com/"                    # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Moritz Friedrich"
theme                    = "sam"
pygmentsStyle            = "native"                                             # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
pygmentsUseClasses       = true
pygmentsOptions = "startinline=1"

[params]
    dateform             = "Monday, 02. January 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                                                # What to call the home page link
    footerText           = ""

    # Metadata for Open Graph and Twitter
    description          = "moritz friedrich, yet another full-stack developer." # Max 160 characters show in search results
    images               = ["hero.png"]                                          # Image that shows on Twitter cards and Open Graph links to the site
    title                = "moritz friedrich"

    # Social pages
    instagramPage        = "radiergummi"
    twitterPage          = "@mofriedrich"
    githubPage           = "Radiergummi"

    # Currently I don't use Analytics at all. I wanted to, but let's face it - I don't look into
    # the statistics anyway. All the hassle the GDPR causes to use Analytics is not worth the
    # trouble, so I'll probably leave it at that.
    analyticsEndpoint    = "https://stats.9dev.de/count"
    analyticsUrl         = "https://stats.9dev.de/count.js"

[[params.mainMenu]]
    link        = "/posts"
    text        = "blog"

[[params.mainMenu]]
    link        = "https://github.com/Radiergummi"
    text        = "github"

[[params.mainMenu]]
    link        = "https://stackoverflow.com/users/2532203"
    text        = "stack overflow"
    hidden      = true

[[params.mainMenu]]
    link        = "/about"
    text        = "who is moritz friedrich?"
    footerText  = "about"

[imaging]
    quality = 75
